volumes:
  data:

services:
  users:
    image: my-golang-app:1
    container_name: users
    ports:
      - 8080:8080
    depends_on:
      - mysql
    
  mysql:
    image: mysql:5.7
    container_name: db_users
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_users
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
