volumes:
  data:

services:
  mysql:
    image: mysql:5.7
    container_name: db_users
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_users
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
